### ISSUE TITLE
How to Refresh/re-download an image

### ISSUE THREAD

**Issue by femski** [frapontillo/ImageViewEx#13]
Great library ! I am using it to show nexrad images to pilots and its a life saver.

One issue I have is that library caches images on disk/memory. This means cached images become outdated as they are updated regularly on the server. Library does not seem to download newer copy of the image from server (restarting app etc does not help). How do I force a refresh of image ?

**Comment by frapontillo** [comment]
You can use [`getMemCache`](https://github.com/frapontillo/ImageViewEx/blob/develop/src/net/frakbot/imageviewex/ImageViewNext.java#L153) and [`getDiskCache`](https://github.com/frapontillo/ImageViewEx/blob/develop/src/net/frakbot/imageviewex/ImageViewNext.java#L158), from there on you can basically do whatever you want with cached objects.
