### ISSUE TITLE
Image alignment messed up in ImageViewNext

### ISSUE THREAD

**Issue by frapontillo** [frapontillo/ImageViewEx#4]
When opening the `ImageViewNextActivity`, the first ImageViewNext has a [custom height](https://github.com/frapontillo/ImageViewEx/blob/feature/cache-rewrite/test/res/layout/next.xml#L20) and a [custom alignment](https://github.com/frapontillo/ImageViewEx/blob/feature/cache-rewrite/test/src/net/frakbot/imageviewex/test/ImageViewNextActivity.java#L53) but it's being showed a little messed up.

@rock3r, can you _please_ spend a couple of minutes on this, since you wrote that? :boar:

**Comment by frapontillo** [comment]
P.S. I'm working on the feature/cache-rewrite branch, could you please work on that as well?

**Comment by rock3r** [comment]
Will do.
